version: '3.7'

services:
  app:
    image: xovenia/crypto-app:latest
    build: server
    volumes:
      - ./server:/var/www/html
      - composer_cache:/var/www/.cache:delegated
    env_file: .env
    networks:
      crypto:
        aliases:
          - app.crypto.internal
  
  web:
    image: xovenia/crypto-web:latest
    build: web
    env_file: .env
    labels:
      - "traefik.http.routers.explorer.entrypoints=web"
      - "traefik.http.routers.explorer.rule=Host(`crypto.local`)"
    environment:
      - NGINX_PHP_FPM_HOST=app.crypto.internal
    networks:
      crypto:
        aliases:
          - web.crypto.internal

  traefik:
    image: traefik:v2.1.3
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env
    networks:
      crypto:
        aliases:
          - traefik.crypto.internal

networks:
  crypto:
    name: crypto-local

volumes:
  composer_cache: